# Generated by Django 5.1.2 on 2024-10-31 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("categories", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("content", models.TextField()),
                (
                    "event_created_at",
                    models.DateTimeField(auto_now_add=True, null=True),
                ),
                ("event_updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("event_ended_at", models.DateTimeField(blank=True, null=True)),
                ("category", models.ManyToManyField(to="categories.category")),
                (
                    "event_author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
