# Generated by Django 5.1.2 on 2024-11-01 08:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="content",
            new_name="description",
        ),
    ]
