# Generated by Django 5.1.2 on 2024-11-01 08:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0002_rename_content_event_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="location",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
