# Generated by Django 5.1.2 on 2024-11-04 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_event_location"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="event_author",
            new_name="event_user",
        ),
    ]
