# Generated by Django 5.1.2 on 2024-11-04 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_rename_event_author_event_event_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="event_user",
            new_name="created_by",
        ),
    ]
