# Generated by Django 5.1.2 on 2024-11-04 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0001_initial"),
        ("events", "0005_rename_event_user_event_created_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="category",
        ),
        migrations.AddField(
            model_name="event",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="categories.category",
            ),
        ),
    ]
