# Generated by Django 5.1.2 on 2024-10-28 19:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_account", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="middle_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
